### ISSUE TITLE
highcharts for columnRange, tooltip layer and datalabel layer overlap

### ISSUE THREAD

**Issue by DStar2013** [highslide-software/highcharts.com#3183] opened 2014-06-23 09:19 UTC
columnRange：

i draw a chart like this ：
![111111](https://cloud.githubusercontent.com/assets/6023530/3355484/893b602e-fab3-11e3-8a3f-4156974355e2.png)

key code like this:
        tooltip: {
            formatter: function() {
                var _str = [];
                _str.push('<b>'+ this.x + '</b><br/>');
                _str.push(this.point.low + '-' + this.point.high + '<br/>');
                if(this.point.percent){
                    _str.push('<b>百分比: </b>' + this.point.percent);
                }
                return _str.join("");
            },
            style: {
                lineHeight: '18px'
            }
        },
        plotOptions: {
            columnrange: {
                colorByPoint: true,
                dataLabels: {
                    enabled: true,
                    overflow: "none",
                    crop: false,
                    formatter: function() {
                        if (this.point.percent && this.point.maxP == this.y) {
                            var _s = [];
                            _s.push("<p class='test'>" + this.x + ": " + this.y + "</p>");
                            _s.push("<p class='test'>" + this.x + "率: " + this.point.percent + "</p>")
                            return _s.join("");
                        }
                    },
                    useHTML: true
                }
            }
        }

beacause i want add new value items in this chart. 

so i use update method:
     var chart = $('#container').highcharts();
     for(var i = 0;i<d.length;i++){
        if(d[i].mark == 1){
            chart.series[0].data[i].update({
                percent: d[i].percent,
                maxP: d[i].maxP
            })
        }
     }

then:
i find that the tooltip layer and datalabel layer overlap 
![333333333](https://cloud.githubusercontent.com/assets/6023530/3355767/74c6986c-fab7-11e3-81ca-6bfd1f20fa21.jpg)

i dont know whether is a bug
so ask for help!

thx

demo address:
http://jsbin.com/ralahodo/11/watch

i tried this attribute: background . And set the opacity 1
But it does not work. still overlap

i find this caused by the attr: 
datalabels { useHTML: true }

**Comment by pawelfus** [comment] 2015-07-09 11:20
Duplicate of #2158

**Closed by pawelfus** 2015-07-09 11:20 UTC
