### ISSUE TITLE
Odd behaviour in tooltip in 4.1.5

### ISSUE THREAD

**Issue by emphasisnet** [highslide-software/highcharts.com#4214] opened 2015-05-21 13:16 UTC
At version 4.1.5, the enhancement regarding the tooltip (switching between series) has strange behaviour when series have irregular intervals. This can be viewed at official demo:
http://www.highcharts.com/demo/spline-irregular-time
For example, if I try to move mouse along the green line, I notice the tooltip moving up-down between series (even if other serie points are very far e.g. at interval 25Jan - 19Apr)

Is there any workaround to face this?

Thank you.

**Comment by highslide-software** [comment] 2015-05-22 07:26
Duplicate of #4128 (fixed). Here's the demo with the fixed code: http://jsfiddle.net/highcharts/kp5ku7hg/

**Closed by highslide-software** 2015-05-22 07:26 UTC
