### ISSUE TITLE
plotOptions.series.point.events.mouseOver event fired twice on bar and column charts

### ISSUE THREAD

**Issue by dugokontov** [highslide-software/highcharts.com#4476] opened 2015-08-17 02:04 UTC
`mouseOver` event on `plotOptions.series.point` is fired twice, with different timestamp, only when chart type is `bar` or `columns`. Here is example on jsfiddle that does `console.log` on event:

http://jsfiddle.net/mjqbr074/

If you change chart type to `line`, it will not be fired twice.

Only way to distinguish those two events was to look for `event.delegateTarget.state`. If it has value `hover` it could be ignored.

**Comment by pawelfus** [comment] 2015-08-17 08:21
Duplicate of #4448

**Closed by pawelfus** 2015-08-17 08:21 UTC
