### ISSUE TITLE
New data is not resetting Negative Colour

### ISSUE THREAD

**Issue by garybrain** [highslide-software/highcharts.com#2966] opened 2014-04-25 09:14 UTC
Hi, found that when you load new data from a ajax query and a value goes from negative to positive the colour is not reset.

http://jsfiddle.net/kCHpY/3/

Thanks

**Comment by pawelfus** [comment] 2015-08-17 15:55
Fixed on bugfix branch: http://jsfiddle.net/kCHpY/6/
Duplicate of #4267.

**Closed by pawelfus** 2015-08-17 15:55 UTC
Labels: Bug
