### ISSUE TITLE
Drilldown: recreated chart after destroying chart while in drilldown disables drilldown to that point

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4004] opened 2015-03-17 15:10 UTC
After destroying chart in drilldown level drilldown to same point is disabled in recreated chart.

Fiddle: http://jsfiddle.net/dxdzdw5q/
Steps: 
1. Drilldown into Animals series. 
2. Re-initialise the chart. 
3. Try to drilldown into the animals series again.

Possible workaround send by forum user:
Clear out the dupes array at the start of doDrilldown (approx line 515 in drilldown.src.js).
More information: http://forum.highcharts.com/highcharts-usage/issue-with-drilldown-after-destroying-and-re-creating-chart-t32501/

**Comment by highslide-software** [comment] 2015-03-18 08:07
Duplicate of #3990 (Fixed)

**Closed by highslide-software** 2015-03-18 08:07 UTC
Labels: Duplicate
