### ISSUE TITLE
Highstock: stacked column - events triggered for wrong column

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4026] opened 2015-03-23 12:15 UTC
Example: http://jsfiddle.net/L8bjo4fa/2/

Clicking on stacked columns will trigger event for column below one clicked if click is performed on lower half of column. In other words:
1. Click lower half of any black column (Joe series)
2. Event is triggered for green column (Jane series)

**Comment by stephanevanraes** [comment] 2015-03-23 12:22
It seems to work in the latest master branch.
Is this a duplicate of #4020 or maybe even #3985.

**Closed by stephanevanraes** 2015-03-23 12:22 UTC
