### ISSUE TITLE
During adding points to area chart, fill color becomes transparent

### ISSUE THREAD

**Issue by stanleyxu2005** [highslide-software/highcharts.com#4524] opened 2015-08-31 04:08 UTC
I have a chart `type=area` with two data series `stacked=0, stacking='normal', animation=false`. Series 1 has fill color blue, series 2 has fill color green. Everything is just fine, but when I add new data points to both series (x-axis is datetime), the fill area will become shortly transparent (see pic left), until the animation is finished (see pic right).
![hc](https://cloud.githubusercontent.com/assets/5162687/9571940/3d70a3e4-4fd9-11e5-9bcd-affd32014066.png)

Have I missed some property to make this right, or is it a known bug?

**Comment by pawelfus** [comment] 2015-08-31 10:09
It's duplicate of #1841

**Closed by pawelfus** 2015-08-31 10:09 UTC
