### ISSUE TITLE
Rest Zoom button not working on IE10

### ISSUE THREAD

**Issue by ValentinH** [highslide-software/highcharts.com#3950] opened 2015-03-06 16:26 UTC
I have noticed that a simple click on the Reset Zoom button doesn't work on IE10. Instead, I need to do a double-click on this button. Is this a expected behaviour?

It was working correctly on 4.0.0 version of Highcharts.

Moreover, we can see that the style of the button stay stuck on the hover effect after a simple click.

Example: http://jsfiddle.net/4s9gapas/

**Comment by highslide-software** [comment] 2015-03-09 08:49
It is fixed in the latest development branch: http://jsfiddle.net/highcharts/4s9gapas/1/

It was caused by the same issue as #3865.

**Closed by highslide-software** 2015-03-09 08:49 UTC
