### ISSUE TITLE
Wrong slice label displaying on 3d pie

### ISSUE THREAD

**Issue by augun** [highslide-software/highcharts.com#3549] opened 2014-10-29 14:05 UTC
While running the code on http://jsfiddle.net/uhydP/225/ , the label 8.87% is moved to the black area.
It is the same code as on http://jsfiddle.net/jugal/uhydP/ which works fine, just without 3d options added.

**Comment by augun** [comment] 2015-01-12 13:38
Dear Torstein,
Are there any solutions for this kind of issue?

**Comment by pawelfus** [comment] 2015-11-05 11:28
Duplicate of #3259

**Closed by pawelfus** 2015-11-05 11:28 UTC
