### ISSUE TITLE
Plot option label not align correctly on bar chart with IE & FF

### ISSUE THREAD

**Issue by apiel** [highslide-software/highcharts.com#3855] opened 2015-02-19 10:16 UTC
When I open the following link on IE and FF the plot option label doesn't align correctly. (Work well on chrome)

http://www.highcharts.com/demo/bar-basic
See value 31 and 4054

**Comment by highslide-software** [comment] 2015-02-19 10:34
Duplicate of #3842

**Closed by highslide-software** 2015-02-19 10:34 UTC
