### ISSUE TITLE
Pie drilldown chart - datalabel html text after drill up stays hidden

### ISSUE THREAD

**Issue by kjm** [highslide-software/highcharts.com#3909] opened 2015-02-27 21:40 UTC
As in title.
Working example - http://jsfiddle.net/1b1huqjp/

Regards

**Comment by bolotniuk-oles** [comment] 2015-06-12 11:09
Same issue, resolved by adding hack into the "redraw" event of a chart:

$('.highcharts-data-labels .null').each(function() {  
	$(this).css('visibility','visible');
});

**Comment by pawelfus** [comment] 2015-06-18 13:33
Another workaround is to set `useHTML: false` or just disabled that option: http://jsfiddle.net/1b1huqjp/2/

**Comment by sebastianbochan** [comment] 2015-07-08 13:12
+1

**Comment by highslide-software** [comment] 2015-07-09 08:02
The issue probably comes down to [this simple test case](http://jsfiddle.net/highcharts/8N3Sz/20/), a HTML label being unable to show again after being hidden.

**Closed** 2015-07-09 08:42 UTC
Labels: Bug

**Comment by ajitrishabh** [comment] 2017-11-24 03:48
@pawelfus  as you said to set `useHTML: false` 
but i can see in the example of drilldown the issue is still there after using  `useHTML: false`  also i can not see column datalable after drilldown.
below is the link. pls click any column and then come back you won't see datalabel.

[http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-drilldown/]

**Comment by pawelfus** [comment] 2017-11-24 09:51
Hi @ajitrishabh 

In current version it's bugged, but we have already fixed this issue: http://jsfiddle.net/bdrdzsg2/ - next release will include the fix.
