### ISSUE TITLE
Download PDF, JPEG, PNG from line chart with data labels, labels duplicated and cutoff

### ISSUE THREAD

**Issue by garethalewis** [highslide-software/highcharts.com#4386] opened 2015-07-13 15:40 UTC
On the highcharts demo page, you can see the issue with exporting to PDF, JPEG, and PNG (SVG is OK). The labels will be duplicated below and cut off so you see the top half of the label the second time below. This is also happening with bar chart labels and possibly other charts. 

Browser (for Windows):
Google Chrome 43.0.2357.132 m
IE 11
Firefox 38.0.5

http://www.highcharts.com/demo/line-labels 

![chart 2](https://cloud.githubusercontent.com/assets/10167924/8653640/69c72226-2953-11e5-87e3-11f22b4235c9.png)

**Comment by pawelfus** [comment] 2015-07-14 08:21
Duplicate of #3649

**Closed by pawelfus** 2015-07-14 08:21 UTC
