### ISSUE TITLE
Pointer.runPointActions error when shifted point has not been redrawn()

### ISSUE THREAD

**Issue by Forusim** [highslide-software/highcharts.com#3769] opened 2015-01-30 14:40 UTC
Hello.
I am using many dynamically updated highcharts(version 4.0.4) in my web application.
I can be 10 or more smaller charts, which display live data.
But those charts are stored in elements, which can be hidden.
When adding a new point to the series, I check for visibility before doing redraw to save performance. I my fiddle I just use a checkbox "GUI Update" to simulate this.

Please check the fiddle:
http://jsfiddle.net/Forusim/vqLnv9rr/1/

The problem is, when the old point is shifted and no redraw() happens, a mouseover will cause:
Uncaught TypeError: object is not a function        highcharts.js:9147 
Pointer.runPointActions                                         highcharts.js:9147
Pointer.onContainerMouseMove                           highcharts.js:9489
Pointer.setDOMEvents.container.onmousemove   highcharts.js:9576

The error will occur here:
// a new point is hovered, refresh the tooltip
if (point && point !== hoverPoint) {

    // trigger the events
    point.onMouseOver(e);

}

point itself is not null, but all it´s properties are null.

So I think the check should be more accurate here. Or the point should be properly removed on series.addPoint(point, redraw=false, shift=true)

Any ideas how to solve this?
Thank you!

**Comment by highslide-software** [comment] 2015-02-02 08:26
Probably a duplicate of #3724. Can you verify that that fix also fixes your issue?

**Comment by Forusim** [comment] 2015-02-02 10:54
You are right, its exactly the same case.
Suggested fix makes sense and works.
Sorry for duplicate ticket, thank you very much!

**Closed** 2015-02-02 19:31 UTC
Labels: Pending reply
