### ISSUE TITLE
Pie Chart does not work with highstock 2.1

### ISSUE THREAD

**Issue by thomdask** [highslide-software/highcharts.com#3823] opened 2015-02-17 09:03 UTC
After the latest release of highcharts/highstock it seems that the highstock js file is not a superset of highcharts anymore since the pie chart generates a js error.
The following jsfiddle is the example from the demo page used with the highstock instead of highcharts.
http://jsfiddle.net/zL01rs40/

The error reported is Uncaught TypeError: Cannot read property 'options' of undefined

**Comment by highslide-software** [comment] 2015-02-17 09:10
Duplicate of #3817

**Closed by highslide-software** 2015-02-17 09:10 UTC
