### ISSUE TITLE
minTickInterval no print minor ticks after last tick

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4266] opened 2015-06-05 11:36 UTC
Example: http://jsfiddle.net/qo8q3mpo/2/

**Comment by pawelfus** [comment] 2015-07-22 11:36
Minified demo: http://jsfiddle.net/qo8q3mpo/5/ 

In general, minor ticks are not rendered before/after min/max of the axis.

**Comment by pawelfus** [comment] 2015-07-22 11:36
Duplicate of #1498

**Closed by pawelfus** 2015-07-22 11:36 UTC
