### ISSUE TITLE
Export: Demo page preview is failing on percent sign

### ISSUE THREAD

**Issue by gvaartjes** [highslide-software/highcharts.com#4213] opened 2015-05-21 11:00 UTC
Export server demo page previews the data by async POST

The data send to the server isn't encode, by using for example a percent sign, the request is misinterpreted. 

Solution is to urlencode the datastring which is send async to the server.

Test the use case with the code below

```js
{
 title: {
            text: 'Browser market shares at a specific website, 2014'
        },

        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                      formatter: function() {
                        return '<b>'+ this.point.name +'</b>: '+
this.percentage +' %'; },

                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Browser share',
            data: [
                ['Firefox',  45.0],
                ['IE',      26.8],
                {
                    name: 'Chrome',
                    y: 12.8,
                                  },
                ['Safari',    8.5],
                ['Opera',    6.2],
                ['Others',  0.7]
            ]
        }]
};
```

**Comment by highslide-software** [comment] 2015-05-21 11:37
Duplicate of #4212

**Closed by highslide-software** 2015-05-21 11:37 UTC
Labels: Bug
