### ISSUE TITLE
Drilldown: axes not aligned after drillup and series hide/show

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4720] opened 2015-11-06 12:19 UTC
Extremes of aligned axes are auto calculated before drilldown and after drillup on starting level. In both cases axes are aligned at start, but they are different. This is causing misalignment of ticks when axis gets hidden and shows back (e.g. through hide/show all series of the axis).

Example: http://jsfiddle.net/j7fsbdfk/
Steps:
0. Ticks are aligned and extremes for axes are 0,30 and 420,480.
1. Click column or axis label to drill down.
2. Click "Back to Planned" button. Ticks are now aligned and maxes for axes are 0,40 and 430,470.
3. Click line series legend item to hide and again to show. 
4. Extremes for right side axis will return to 420,480. Ticks are not aligned.

**Comment by pawelfus** [comment] 2015-11-06 12:30
Looks like duplicate of: #4374

Workaround: http://jsfiddle.net/j7fsbdfk/1/

**Comment by highslide-software** [comment] 2015-11-11 10:35
Duplicate of #4374 (fixed).

**Closed by highslide-software** 2015-11-11 10:35 UTC
Labels: Duplicate
