### ISSUE TITLE
Multiple yaxis causes wrong padding (threshold) cause of alignTicks

### ISSUE THREAD

**Issue by onemenny** [highslide-software/highcharts.com#4727] opened 2015-11-09 16:47 UTC
It seems that having the exact series twice, once with yaxis at index 0 and another with a yaxis at index 1 (opposite) causes the yaxsis padding at the top increase. 

Please see: http://jsfiddle.net/onemenny/zw4zs506/
If you change the second series yaxis index to 0 you will see the padding decrease (which is the correct behaviour). 

If you set the alignTicks to false than it works as expected, but if the series (0 and 1) is the same how come the ticks are different and causing the padding to increase?

**Comment by onemenny** [comment] 2015-11-10 09:43
Another issue related: 
Now I set alignTicks to true, yaxis gets startOnTick and endOnTick set to false, which results in both yaxises gridline display not aligned 

http://jsfiddle.net/onemenny/zw4zs506/2/

Please advice

**Comment by pawelfus** [comment] 2015-11-10 12:42
First issue looks like duplicate of #4580, and second one connected to #4374.

**Comment by onemenny** [comment] 2015-11-11 07:58
any estimation on that?

**Comment by highslide-software** [comment] 2015-11-11 09:47
Duplicate of #4580

**Closed by highslide-software** 2015-11-11 09:47 UTC
Labels: Duplicate

**Comment by highslide-software** [comment] 2015-11-11 10:36
#4374 is fixed now.
