### ISSUE TITLE
Datalabels render twice when exporting large images

### ISSUE THREAD

**Issue by c0n3j0** [highslide-software/highcharts.com#4516] opened 2015-08-27 11:23 UTC
Can be reproduced at the official example:

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-basic/

At the resulting image you will see a second datalabel below the original.

**Comment by pawelfus** [comment] 2015-08-27 12:09
Duplicate of #3649.

**Closed by pawelfus** 2015-08-27 12:09 UTC
