### ISSUE TITLE
buildKDTree - startRecursive fails cause series has null points array

### ISSUE THREAD

**Issue by onemenny** [highslide-software/highcharts.com#4390] opened 2015-07-15 06:57 UTC
for the kd tree this code gets called with setTimeout. during the setTimeout a series can be removed (e.g. series.remove()) which causes the grep to fails cause series.points is null/undefined. series.points should be tested before the grep operation. 

```javascript
// Start the recursive build process with a clone of the points array and null points filtered out (#3873)
		function startRecursive() {
			var points = grep(series.points, function (point) {
				return point.y !== null;
			});
			series.kdTree = _kdtree(points, dimensions, dimensions);		
		}

		delete series.kdTree;
		
		if (series.options.kdSync) {  // For testing tooltips, don't build async
			startRecursive();
		} else {
			setTimeout(startRecursive);
		}
```

**Comment by gvaartjes** [comment] 2015-07-16 14:25
Thanks will we look into it.  Please take into account a bit longer response time, due to the vacation period

**Comment by onemenny** [comment] 2015-08-04 08:09
is there anything new?

**Comment by highslide-software** [comment] 2015-08-04 08:31
Sorry for the delay!

You didn't describe how to reproduce the issue, but probably it will be resolved by simply grepping an empty array if `series.points` is falsy:

´´´js
var points = grep(series.points || [], function (point) {
´´´

Please test this, and I'll add it if it works for you.

**Comment by onemenny** [comment] 2015-08-04 10:32
yes, this solves the problem of course.  will it be out on the next minor version?

this happens while hovering the chart (tooltip) and in the background changing the series (reload)

**Comment by highslide-software** [comment] 2015-08-05 07:02
> will it be out on the next minor version?
Yes

**Closed** 2015-08-05 07:02 UTC
