### ISSUE TITLE
3d: opposite yAxis - labels wrongly placed when scale is smaller comparing to other yAxis

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4591] opened 2015-09-22 12:31 UTC
In 3d chart with multiple y axes. Scale of opposite yAxis is much smaller that scale of other yAxis (doesn't matter if the other yAxis is opposite or not). Labels of the problematic yAxis are wrongly placed - moved to left. Issue is more visible if a difference between scales is bigger.

Example:  http://jsfiddle.net/uneb9jLc/2/

**Comment by pawelfus** [comment] 2015-09-22 13:22
Duplicate of #3788

**Closed by pawelfus** 2015-09-22 13:22 UTC
