### ISSUE TITLE
Stacked area chart path is empty during transition

### ISSUE THREAD

**Issue by bripkens** [highslide-software/highcharts.com#4297] opened 2015-06-17 14:25 UTC
See the following demo: http://jsfiddle.net/zsxfkqor/

The paths do not have a visible fill color because the paths are empty. SVG paint instruction: `M 0 0` is all that is left.

**Comment by pawelfus** [comment] 2015-06-17 14:30
Duplicate of #169

**Closed** 2015-06-25 07:29 UTC
