### ISSUE TITLE
yAxis : Special characters are displayed when the text is too large

### ISSUE THREAD

**Issue by ptijul** [highslide-software/highcharts.com#4665] opened 2015-10-15 09:00 UTC
Under certain circumstances, the end of the yAxis-title is cropped and replaced by special characters.
The first screenshot shows the problem.

Steps to reproduce (1st screenshot) - NOT ok version:
1. Resize the browser to have a smaller width => The graph is properly resized and the yAxis are displayed differently (see 2nd screenshot)
2. Refresh the page : 
OBSERVED RESULT: The graph is drawn with the available space but the yAxis are not properly displayed.
EXPECTED RESULT:  The yAxis should either crop the remaining text and replace with "..." or being rendered same as the 2nd screenshot (obtained with help of a window resizing).

I know the solution (refresh the page) seems to be obvious, but the graphs are viewed by our clients and their technical skills are very low for some so this is a problem for my management and the marketing team. 

![nok](https://cloud.githubusercontent.com/assets/8395615/10508686/e3ac9854-7328-11e5-825d-a5fbd583f2d3.png)
![ok](https://cloud.githubusercontent.com/assets/8395615/10508687/e3af3168-7328-11e5-9646-b17c4d5be959.png)

Version: 
- Highcharts : 4.1.7
- Bootstrap : 3.1.1
- Browser : FF 41.0.1, IE 10, Chrome 45.0

Encoding : iso-8859-1

Thanks !

**Comment by highslide-software** [comment] 2015-10-15 13:00
Thanks for the bug report. Can you share a live reproduction with us? I tried here, but maybe you can change it to display the bug? http://jsfiddle.net/highcharts/5znp55oa/

**Comment by pawelfus** [comment] 2015-10-15 13:17
I think this is the problem: 

> Encoding : iso-8859-1

**Comment by ptijul** [comment] 2015-10-15 16:15
Thanks both of you for your reply and the effort you made for jsfiddle sample.

@pawelfus: You're right ! The problem is the encoding. I've made a sample page with an HTML table and the graphic based on it. The encoding is ISO-8859-1 => reproducible. Not with UTF-8 :+1: 
I'll check to base this part of the application with UTF-8...not sure if mixing two encoding in the same website is a very good idea :-(

Should we keep this issue open? How can I change the encoding in the jsfiddle to give you a reproducible sample ?

**Comment by highslide-software** [comment] 2015-10-19 11:59
I think we can close it, because the difference in encoding makes Highcharts split the strings in the wrong place.

**Closed by highslide-software** 2015-10-19 11:59 UTC
Labels: Cant reproduce
