### ISSUE TITLE
Duplicate dataLabel text of column/bar chart in ipad/safari

### ISSUE THREAD

**Issue by dongyingtao** [highslide-software/highcharts.com#3910] opened 2015-02-28 07:28 UTC
This doesn't repro on chrome. Only repro in Safari of my iPad. Stacking label works well, using it as work around now.

**Comment by dongyingtao** [comment] 2015-02-28 07:29
ipad version 8.1.2

**Comment by highslide-software** [comment] 2015-03-02 08:02
Duplicate of #3911

**Closed by highslide-software** 2015-03-02 08:02 UTC
