### ISSUE TITLE
Cannot alter X-axis while exporting

### ISSUE THREAD

**Issue by BrainCrumbz** [highslide-software/highcharts.com#3848] opened 2015-02-18 17:10 UTC
Kind of related to issue #1562 

when configuring chart, we're passing also the `exporting` field as:

          exporting: {
            filename: 'some-file-name',  // default exported filename
            buttons: { 
              ...
            },
            chartOptions: {
              title: {
                text: 'Dummy text when exporting',
              },
              xAxis: {
                lineColor: '#FF0000',  // some color
                tickInterval: _millisecsInAMonth,  // try to force 1 tick per month
              },
            },
          },

In the exported picture (with the filename expected) we can see the title as set, but we cannot see any change on the x-axis, that stays as in the displayed chart.

Although if we pass `xAxis: null,`, we can see that the original datetime formatting and every other custom axis setting is completely gone.

Is there a reference on what options can be *altered* for exporting?

Thanks

**Comment by BrainCrumbz** [comment] 2015-02-18 17:24
Actually there seems to be more issues similar to this: #2022 , #1759.

**Comment by highslide-software** [comment] 2015-02-19 12:40
Duplicate of #2022 (fix coming up)

**Closed by highslide-software** 2015-02-19 12:40 UTC
