### ISSUE TITLE
Pie chart labels are duplicated in Safari

### ISSUE THREAD

**Issue by houmark** [highslide-software/highcharts.com#3943] opened 2015-03-05 18:17 UTC
Safari is showing duplicated labels for slices in Highcharts version 4.1.2+.

Below is the official demo pie using 4.1.1 and latest Highcharts - please use Safari to recreate this bug:

Latest (with bug):
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-basic/

Same pie, just using 4.1.1 (no bug):
http://jsfiddle.net/u4oe0pux/

Chrome seems fine. Did not test Firefox yet. I thought first it might be my code that was wrong, but since the demo from the Highcharts website is also doing it, this must be a problem within Highcharts specifically with Safari.

I'm on Mac OS X Yosemite 10.10.2 using Safari 8.0.3.

**Comment by highslide-software** [comment] 2015-03-06 11:05
Duplicate of #3911 (fixed)

**Closed by highslide-software** 2015-03-06 11:05 UTC
