### ISSUE TITLE
yAxis: hide/show series draws vertical grid lines incorrectly (it doubles them)

### ISSUE THREAD

**Issue by dmitrygorbenko** [highslide-software/highcharts.com#4673] opened 2015-10-20 16:41 UTC
Check this example:  http://jsfiddle.net/zvsgvkp2/
Try to click on "Series 1" and "Series 2" to hide them and click again to show them -- you'll notice changes in vertical lines.

Seems like a bug. Tested on Master branch.

Thanks,
Dima

**Comment by pawelfus** [comment] 2015-10-21 14:27
Duplicate of #4374

**Closed by pawelfus** 2015-10-21 14:27 UTC
