### ISSUE TITLE
Superimposed and duplicated labels when exporting pie chart

### ISSUE THREAD

**Issue by helenej** [highslide-software/highcharts.com#4224] opened 2015-05-25 14:58 UTC
When adding a line break in labels of a pie chart, PNG export won't work correctly (labels are duplicated and superimposed), as you can see here: http://jsfiddle.net/b7yzjk02/ (browser is Firefox).

Thank you in advance.

**Comment by highslide-software** [comment] 2015-05-26 08:05
Duplicate of #3649

**Closed by highslide-software** 2015-05-26 08:05 UTC
Labels: Duplicate
