### ISSUE TITLE
4.1.4 no longer returns points from both series in shared tooltip formatter

### ISSUE THREAD

**Issue by SteveSchreiner** [highslide-software/highcharts.com#4019] opened 2015-03-20 20:18 UTC
After upgrading from 4.0.4 to 4.1.4, we are no longer getting the points back that we were during a shared tooltip formatter.  

See this fiddle which uses 4.0.4 and notice how points from both series appear in shared tooltip:
http://jsfiddle.net/ttbsoftware/5ybkv37L/1/

See this fiddle that uses 4.1.4 and notice how only one point appears in shared tooltip:
http://jsfiddle.net/ttbsoftware/5ybkv37L/2/

**Comment by stephanevanraes** [comment] 2015-03-23 07:56
Duplicate of #3967

**Closed by stephanevanraes** 2015-03-23 07:56 UTC
