### ISSUE TITLE
Updating point in candlestick causes it to disappear

### ISSUE THREAD

**Issue by bjackson** [highslide-software/highcharts.com#4326] opened 2015-06-25 21:58 UTC
See this fiddle: http://jsfiddle.net/bjacksoneze/9L9u1eye/16/

Whenever I attempt to change an attribute on the candlestick, in this case: close, it appears for a small fraction of a second then disappears.

**Comment by highslide-software** [comment] 2015-06-26 06:49
Duplicate of #4284.

Demo with the fix applied: http://jsfiddle.net/highcharts/9L9u1eye/17/

Until our next maintenance release, you can use the previous version of Highstock (2.1.5).

**Closed by highslide-software** 2015-06-26 06:49 UTC
