### ISSUE TITLE
Export 3d stacked column with floating legend chart can cause rendering artifacts

### ISSUE THREAD

**Issue by kingoleg** [highslide-software/highcharts.com#4472] opened 2015-08-13 15:20 UTC
jsfiddle: http://jsfiddle.net/n4Lvv4cv/3/

What I do:
Open jsfiddle
Run and "Download..." button

What I see:
1 138.21
       8.21
on top of the first column

What is expected:
No rendering artifacts

If I remove 3d option, or floating for legend, or stacking - problem is gone.
Problem can gone with other data.
Some times the problem affects more then 1 column.
Some times it duplicates the total values of column

**Comment by kingoleg** [comment] 2015-08-13 15:23
The problem is gone if only integer numbers are used in data

**Comment by pawelfus** [comment] 2015-08-13 15:29
Duplicate of #3649.

**Closed by pawelfus** 2015-08-13 15:29 UTC
