### ISSUE TITLE
tooltip is displayed for points out of area

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4348] opened 2015-07-02 11:48 UTC
Example: http://jsfiddle.net/zojkxg1h/11/

Steps to reproduce:
1) hover over violet series 
2) move cursor to right direction

**Comment by sebastianbochan** [comment] 2015-07-07 11:35
Next example: http://jsfiddle.net/s2gfjLph/

**Comment by pawelfus** [comment] 2015-07-07 11:59
Duplicate of #4149

**Closed by pawelfus** 2015-07-07 11:59 UTC

**Comment by sebastianbochan** [comment] 2015-07-08 14:32
Related case #3916
