### ISSUE TITLE
Highstock: flags outside plot area

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3991] opened 2015-03-16 12:35 UTC
Example: http://jsfiddle.net/12js2yd1/

Flags are outside plot area (overlaying range selector buttons and after manipulating navigator flags can overlay chart context menu).

In that fiddle is also present problem with tooltip that is displayed over flags (when hovering over flags).

**Comment by prettycode** [comment] 2015-03-17 14:06
This is what I use as the workaround:

http://jsfiddle.net/12js2yd1/7/

**Comment by highslide-software** [comment] 2015-03-18 09:46
Duplicate of #419

**Closed by highslide-software** 2015-03-18 09:46 UTC
Labels: Duplicate

**Comment by dev-katiyar** [comment] 2021-05-25 17:19
try this https://api.highcharts.com/highstock/plotOptions.flags.clip
