### ISSUE TITLE
Legend width doesn't take into account navigation buttons

### ISSUE THREAD

**Issue by dejongch** [highslide-software/highcharts.com#2583] opened 2014-01-10 16:48 UTC
The width of the legend can be too skinny to fit the navigation buttons

http://jsfiddle.net/j7LPX/

**Comment by pawelfus** [comment] 2015-08-25 15:25
Duplicate of #3455 

Working demo: http://jsfiddle.net/j7LPX/1/

**Closed by pawelfus** 2015-08-25 15:25 UTC
