### ISSUE TITLE
Function wrapping Series.render wrap throws error referencing property on undefined series.xAxis

### ISSUE THREAD

**Issue by jonkafton** [highslide-software/highcharts.com#4366] opened 2015-07-08 22:45 UTC
Affects pie charts. HighStock version 2.1.7, line 23359

See: http://jsfiddle.net/sx4y2y6s/1/

**Comment by highslide-software** [comment] 2015-07-09 07:52
Duplicate of #4350

**Closed by highslide-software** 2015-07-09 07:52 UTC
Labels: Duplicate
