### ISSUE TITLE
plotline with min and max range values isn't paired with correspondig series

### ISSUE THREAD

**Issue by cirux** [highslide-software/highcharts.com#3752] opened 2015-01-26 12:08 UTC
I need multiple series with corresponding yAxis.
Each yAxis should have min and max values ranges.
Series are selectable / deselectable: when I click on a series, it disappears with it's min-max plotilines.
When a series has only min or only max plotLine, all things works.
If a series has both min and max plotLines, these are not deleted when I delesect the corresponding series.
JFiddle reproducing the bug (third series): http://jsfiddle.net/cirux/4cg9eh75/
Bug found while working on Google Chrome

**Comment by highslide-software** [comment] 2015-01-27 09:44
The rationale is that you set axis min and max, thereby the axis knows its extremes, and is able to render. Including plot bands and lines. If you only set one of them, it doesn't know how to render and all associated items are hiddden: http://jsfiddle.net/highcharts/4cg9eh75/2/ .

So this issue ultimately is a duplicate of #705.

**Closed by highslide-software** 2015-01-27 09:44 UTC

**Comment by cirux** [comment] 2015-01-27 21:31
Thanks for the explanation. This is strange: using Chrome on Ubuntu, I haven't that problem (when I reported the bug, I was working on Windows)
