### ISSUE TITLE
Issue using {series.name} in headerFormat in highStock

### ISSUE THREAD

**Issue by ortegafernando** [highslide-software/highcharts.com#3572] opened 2014-11-07 11:30 UTC
Hi, 

In this example, 

http://www.highcharts.com/stock/demo/basic-line
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/

 if I add in SERIES - TOOLTIP this:

                    headerFormat: '<b>{series.name}</b><br>',

The chart doesnt show the series's name, instead, it show "{series.name}" string

Highchart works perfect, highStock doesn't.

Cheers,

**Comment by sebastianbochan** [comment] 2015-10-28 16:15
Related with: https://github.com/highslide-software/highcharts.com/issues/3238

**Comment by highslide-software** [comment] 2015-10-30 09:39
Duplicate of #3238.

**Closed by highslide-software** 2015-10-30 09:39 UTC
Labels: Duplicate
