### ISSUE TITLE
Interactive legend and Scroll bar issue

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4693] opened 2015-10-27 14:25 UTC
http://jsfiddle.net/pawanvjadhav/gz70zfzv/1/

1) Open above url
2) Click on legend item and hide series (i.e. hide series by clicking "id" legend)
3) Move scrollbar towards right (after hiding series)
4) Click on legend item to show series.
5) See series is not getting displayed you have to move scroll to show series again,

**Comment by pawelfus** [comment] 2015-10-27 14:45
Duplicate of #1195 
Works fine when navigator is enabled: http://jsfiddle.net/gz70zfzv/3/

**Closed by pawelfus** 2015-10-27 14:45 UTC

**Comment by pawanvjadhav** [comment] 2015-10-28 04:37
But what if, someone don't want to use navigator.? 
It takes lot of space.

**Comment by pawanvjadhav** [comment] 2015-10-28 06:01
reviewed #1195. Tis is looks like a patch work. I cant put this in our product.

**Comment by pawanvjadhav** [comment] 2015-10-28 06:01
Could you pls think of fixing this?

**Comment by pawanvjadhav** [comment] 2015-11-04 07:27
Any comment on this?

**Comment by pawelfus** [comment] 2015-11-04 10:43
Please, open connected issue - it is already fixed and closed. You can check this using master branch: http://github.highcharts.com/master/highstock.src.js

**Comment by pawanvjadhav** [comment] 2015-11-13 11:56
Ok. its working  :+1: 

Thank You!!
