### ISSUE TITLE
Gauge - dial looses some of style options after point.update

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3779] opened 2015-02-02 14:36 UTC
In gauge type series - dial looses some of style options (colors, border width) after point.update

Example: http://jsfiddle.net/xvydwz9o/

**Comment by pawelfus** [comment] 2015-06-18 12:06
Looks fine on a master branch: http://jsfiddle.net/xvydwz9o/1/

**Comment by highslide-software** [comment] 2015-06-23 08:39
Probably duplicate of #4284.

**Closed by highslide-software** 2015-06-23 08:39 UTC

**Comment by KacperMadej** [comment] 2015-06-29 12:17
Not working for master branch: http://jsfiddle.net/xvydwz9o/2/

**Comment by highslide-software** [comment] 2015-06-29 13:20
Workaround: Set the new value as an integer, not in an object syntax.
