### ISSUE TITLE
Chart Labels print twice on Window 8, IE 11

### ISSUE THREAD

**Issue by mjfaga** [highslide-software/highcharts.com#4627] opened 2015-10-05 21:02 UTC
In IE 11.0.9600.18036 (Update Versions: 11.0.23 - KB3087038) on a Windows 8, the chart labels print out twice when "Save as image" option is used and either PNG, JPEG, or PDF options are selected.
* Currently using current version of Highcharts v4.1.8
* Doesn't happen in Chrome 45.0.2454.101

JSFiddle to reproduce issue: http://jsfiddle.net/t3av5cr0/3/

Sample export:
![chart](https://cloud.githubusercontent.com/assets/7584015/10293465/a01dfb08-6b82-11e5-9e7a-d4cb09cffdb9.jpeg)

**Comment by highslide-software** [comment] 2015-10-06 07:59
Duplicate of #3649.

The workaround is to disable text-shadow: http://jsfiddle.net/t3av5cr0/4/

**Comment by highslide-software** [comment] 2015-10-06 08:34
Reopening this. The new issue is that it is fixed in Chrome by upgrading PhantomJS on the server, but this doesn't apply to IE11/Edge.

**Closed** 2015-10-06 08:54 UTC
Labels: Duplicate

**Comment by mjfaga** [comment] 2015-10-06 14:19
Any idea when this update will be released?

**Comment by highslide-software** [comment] 2015-10-07 07:19
Yes, probably today :D
