### ISSUE TITLE
plotBands outside the range render labels

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3989] opened 2015-03-16 10:03 UTC
Example:

- v2.1.1: http://jsfiddle.net/gwbmu9ts/1/
- v2.1.4: http://jsfiddle.net/gwbmu9ts/2/

plotBands aren't within actual extremes, but labels are still rendered.

**Comment by highslide-software** [comment] 2015-03-18 10:22
Duplicate of #3983

**Closed by highslide-software** 2015-03-18 10:22 UTC
Labels: Duplicate
