### ISSUE TITLE
Spiderweb - error thrown if tooltip disabled

### ISSUE THREAD

**Issue by krishan711** [highslide-software/highcharts.com#4255] opened 2015-06-02 11:02 UTC
I've bene playing around with the spiderweb chart type, and it looks like javascript error occurs if tooltips for that chart are disabled. Please see my fiddle below as an example.

http://jsfiddle.net/vtk4at79/1/

**Comment by highslide-software** [comment] 2015-06-02 12:43
Duplicate of #4116, fixed.

**Closed by highslide-software** 2015-06-02 12:43 UTC
Labels: Duplicate
