### ISSUE TITLE
Rendering logic is broken for data labels / legend toggles

### ISSUE THREAD

**Issue by seiyria** [highslide-software/highcharts.com#3889] opened 2015-02-25 17:05 UTC
http://jsfiddle.net/xm9ud2xv/

This breaks on areas and other charts as well.

**Comment by smithk58** [comment] 2015-02-25 18:06
To clarify this more - sometimes if you hide something via the legend random datalabels will be removed.

In the above JS fiddle if you disable John via the legend, then Jane has two datalabels that are removed.

**Comment by highslide-software** [comment] 2015-02-26 11:41
Duplicate of #3866 [Closed]. See http://jsfiddle.net/highcharts/xm9ud2xv/1/.

**Closed by highslide-software** 2015-02-26 11:41 UTC
