### ISSUE TITLE
Flag on first point

### ISSUE THREAD

**Issue by bharathd** [highslide-software/highcharts.com#4621] opened 2015-10-05 08:22 UTC
first flag point is not displayed and after using minPadding it is displaying but when we scroll the navigator then the point is not visible .

**Comment by sebastianbochan** [comment] 2015-10-05 08:51
Duplicate of https://github.com/highslide-software/highcharts.com/issues/3119

**Closed by sebastianbochan** 2015-10-05 08:51 UTC

**Comment by bharathd** [comment] 2015-10-05 09:30
But navigator is issue is there
