### ISSUE TITLE
Zone color is not applied properly, when update column

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4604] opened 2015-09-28 09:55 UTC
In case when we update column, color is not applied properly.

Example: http://jsfiddle.net/bfb6w1qq/1/

For line chart, all works properly.

http://jsfiddle.net/bfb6w1qq/2/

**Comment by pawelfus** [comment] 2015-09-28 10:45
Duplicate of #4267 - works fine on bugfix branch: http://jsfiddle.net/bfb6w1qq/3/

**Closed by pawelfus** 2015-09-28 10:45 UTC
