### ISSUE TITLE
Text contrast no longer works in Chrome

### ISSUE THREAD

**Issue by zealsolutions** [highslide-software/highcharts.com#4560] opened 2015-09-10 21:05 UTC
The "contrast" text shadow around text on pie charts no longer works in Chrome on Mac and Windows, as of Chrome version 45 (it worked fine in 44).

See http://www.highcharts.com/demo/pie-donut and note that "Chrome" and "MSIE" are difficult to read because there's white text with white text shadow on a light background.

This appears to also be an issue in Firefox.

I haven't traced this all the way through, but in SVGRenderer.getContrast() (Around line 3385 in Highcharts 4.1.8), the color parameter is 'white' in Chrome 45, but was '#FFFFFF' in Chrome 44. 'white' does not get parsed by the Color utility class, and therefore the sum of its constituents is NaN, which is not >384, so the return value is '#FFFFFF', not '#000000'.

Example in Chrome 44:
<img width="845" alt="chrome 44 text shadow" src="https://cloud.githubusercontent.com/assets/682503/9800860/68d7d30c-57dd-11e5-9f31-03121e612556.png">

Example in Chrome 45:
<img width="716" alt="chrome 45 text shadow" src="https://cloud.githubusercontent.com/assets/682503/9800925/de9a1ce4-57dd-11e5-97f0-25b0f61e1a67.png">

**Comment by pawelfus** [comment] 2015-09-11 09:20
I think this is duplicate of #4554 ;)

**Closed by pawelfus** 2015-09-11 09:20 UTC

**Comment by zealsolutions** [comment] 2015-09-11 14:19
Ugh, I'm so bad at searching for existing bug reports :( Thanks for the response!
