### ISSUE TITLE
Data labels not rendering correctly when exporting

### ISSUE THREAD

**Issue by Krashlog** [highslide-software/highcharts.com#4422] opened 2015-07-28 19:38 UTC
When exporting a chart as PNG, JPEG or PDF, data labels are "doubled" (over & under each data points). The easiest way to reproduce is to use the demo page "With data labels" and choose "Download PNG image" :

http://www.highcharts.com/demo/line-labels

Here is the result from this export...
![chart](https://cloud.githubusercontent.com/assets/1075078/8941558/46613122-353e-11e5-8d8c-8a2f0c8ebb38.png)

The data labels are not displaying as expected. I don't remember seeing this behavior with 4.1.6, but my guess is that something changed on the export server. I can provide more samples if needed. Thanks.

**Comment by sebastianbochan** [comment] 2015-07-29 13:35
Duplicate of http://www.tripwiremagazine.com/2012/01/wordpress-video-theme.html

**Closed by sebastianbochan** 2015-07-29 13:35 UTC
