### ISSUE TITLE
Visual bug if x values is not sorted

### ISSUE THREAD

**Issue by icebob** [highslide-software/highcharts.com#3929] opened 2015-03-03 14:53 UTC
Issue: http://jsfiddle.net/icebob/98x1oq71/2/

Latest v4.1.3 version.

**Comment by stephanevanraes** [comment] 2015-03-04 07:40
You get an [error 15](http://www.highcharts.com/errors/15) in console.

**Comment by highslide-software** [comment] 2015-03-04 10:51
Duplicate of #1900

**Closed by highslide-software** 2015-03-04 10:51 UTC

**Comment by highslide-software** [comment] 2015-03-04 10:53
Workaround 1: sort the data up front.

Workaround 2: provide a `pointRange` setting: http://jsfiddle.net/highcharts/98x1oq71/3/

**Comment by icebob** [comment] 2015-03-04 11:11
Great!
