### ISSUE TITLE
Disabling the tooltip on a polar chart causes error

### ISSUE THREAD

**Issue by taylorbobj2250** [highslide-software/highcharts.com#4168] opened 2015-05-06 14:59 UTC
Set tooltip.enabled = true, chart renders, set = false, errors...

```js
$(function () {

    $('#container').highcharts({

        chart: {
            polar: true
        },

        title: {
            text: 'Highcharts Polar Chart'
        },

        pane: {
            startAngle: 0,
            endAngle: 360
        },

        xAxis: {
            tickInterval: 45,
            min: 0,
            max: 360,
            labels: {
                formatter: function () {
                    return this.value + '°';
                }
            }
        },

        yAxis: {
            min: 0
        },

        plotOptions: {
            series: {
                pointStart: 0,
                pointInterval: 45
            },
            column: {
                pointPadding: 0,
                groupPadding: 0
            }
        },
        tooltip: {enabled:false},

        series: [{
            type: 'column',
            name: 'Column',
            data: [8, 7, 6, 5, 4, 3, 2, 1],
            pointPlacement: 'between'
        }, {
            type: 'line',
            name: 'Line',
            data: [1, 2, 3, 4, 5, 6, 7, 8]
        }, {
            type: 'area',
            name: 'Area',
            data: [1, 8, 2, 7, 3, 6, 4, 5]
        }]
    });
});
```

**Comment by highslide-software** [comment] 2015-05-07 08:11
Duplicate of #4116, fixed.

**Closed by highslide-software** 2015-05-07 08:11 UTC
