### ISSUE TITLE
legend symbol doesn't show both negativeColor and primary color

### ISSUE THREAD

**Issue by tommyrisom** [highslide-software/highcharts.com#3414] opened 2014-09-07 10:54 UTC
When using the property, negativeColor, on a series, the legend symbol only shows the primary color of the series. 

It should be possible to define (perhaps on a series or globally) that the legend symbol should show both the negativeColor and the primary color. The legend symbol could be colored in half negativeColor and half primary color.

This is even more relevant if all values are negative. Then the line on the chart would be in one color but the legend symbold would be in another color. This will be a bad user experience.

Example AS-IS:
Primary color: green. Negative color: red. Legend symbol: green.
http://jsfiddle.net/ba97mfde/2/

Example TO-BE:
Primary color: green. Negative color: red. Legend symbol red and green.
![image](https://cloud.githubusercontent.com/assets/8553784/4178149/f8d442d0-367b-11e4-9864-15ae21f5133f.png)

**Comment by pawelfus** [comment] 2015-08-17 11:45
Duplicate of #1852.

**Closed by pawelfus** 2015-08-17 11:45 UTC

**Comment by dustinjohnson13** [comment] 2016-03-22 19:12
Why were both this one and #1852 closed?  I understand they were duplicates of each other, but I don't see any functionality added to either of them to resolve the issue.  I'm in the same boat as needing a way to show a positive and negative threshold color in the legend.  Is there a specific way to handle this already?

**Comment by pawelfus** [comment] 2016-03-23 11:19
#1852 ticket is still open

**Comment by dustinjohnson13** [comment] 2016-03-23 11:49
Ah, apparently I'm blind.  Thanks, Pawel.

For other's reference, here's how I solved the problem in the meantime.  For a column chart, I added an additional series with no points and a color of red (so it showed in the legend).  Then I enabled the option `stacking: "normal" to remove the space between the two different series.  A bit hacky, but it gets the job done for my use case.

**Comment by TorsteinHonsi** [comment] 2016-03-29 09:10
Here's an example of how you can extend the legend symbols to draw your own: http://jsfiddle.net/highcharts/ba97mfde/11/
