### ISSUE TITLE
Stacked area chart has holes when using timestamps.

### ISSUE THREAD

**Issue by lorgan3** [highslide-software/highcharts.com#4447] opened 2015-08-10 11:19 UTC
Jsfiddle showing the issue: http://jsfiddle.net/t17wj3eb/4/

These holes can be filled by adding extra timestamps to the series (see commented out code in the fourth series), but I assume this is a bug and Highcharts should do it automatically?

**Comment by highslide-software** [comment] 2015-08-11 08:37
It's because the X values do not align. This is what we have been working on in the `nosegments` branch. See http://jsfiddle.net/highcharts/t17wj3eb/5/.

Duplicate of #2069.

**Closed by highslide-software** 2015-08-11 08:37 UTC
Labels: Duplicate
