### ISSUE TITLE
Series don't update accordingly to zIndex change using update method

### ISSUE THREAD

**Issue by MattNowosielski** [highslide-software/highcharts.com#3740] opened 2015-01-21 20:31 UTC
I am trying to change the depth of each highstock series using zIndex and update method. I am pretty sure this was working in previous versions of high stock and seems like a regression bug to me. Here is jsfiddle for that.

http://jsfiddle.net/manualride/qygLpmnx/1/

As you can see the color is updated, but not the zIndex.

**Comment by MattNowosielski** [comment] 2015-01-30 22:31
Can I get an ETA on when this issue will be fixed?

**Comment by highslide-software** [comment] 2015-02-05 14:14
Duplicate of #3380 (fixed). [The patch](https://github.com/highslide-software/highcharts.com/commit/f4e684987ae40ef21b587c4571dd0bde7f8c6ef9.patch) can be applied to 4.0.4.

**Closed by highslide-software** 2015-02-05 14:14 UTC
