### ISSUE TITLE
In Highstock, IE - range selector ignore enter key

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3690] opened 2014-12-27 19:43 UTC
In Highstock, IE - range selector ignore enter key.

Open i.e. demo - http://www.highcharts.com/stock/demo
1. Change input for range selector
2. Press enter
3. Changes are not applied
To apply changes you need to press tab key.

**Comment by pawelfus** [comment] 2015-07-23 12:15
Duplicate of #3477

**Closed by pawelfus** 2015-07-23 12:15 UTC
