### ISSUE TITLE
MinPointLength on stacked bar chart

### ISSUE THREAD

**Issue by GMartigny** [highslide-software/highcharts.com#4140] opened 2015-04-27 14:51 UTC
Hello,

I tried to add a minPointLength on a percent stacked bar chart in order to visualize empty values. But, it 's not working as expected.
http://jsfiddle.net/f9tzha2s/1/
Point with value to 0 aren't shown and it's quite difficult to compare each stack.
Weirdly, if I comment "reversedStacks: false", minPointLength is effective but not for the last option.

I hope it helps

**Comment by sebastianbochan** [comment] 2015-05-21 11:39
Seems that the same problem with "default stacked bar".

Example: http://jsfiddle.net/0196fv4L/5/

**Comment by Jmaharman** [comment] 2015-05-21 15:42
+1 to both of the above.

**Comment by highslide-software** [comment] 2015-05-22 07:21
Duplicate of #1776

**Closed by highslide-software** 2015-05-22 07:21 UTC
