### ISSUE TITLE
If the xAxis is reversed, the labels are not visible

### ISSUE THREAD

**Issue by mkhlud** [highslide-software/highcharts.com#4595] opened 2015-09-23 16:48 UTC
![image](https://cloud.githubusercontent.com/assets/2544772/10051776/f4e84a68-622b-11e5-9cd7-2405716b8e86.png)

Example: http://jsfiddle.net/mkhlud/z3eje2ge/

**Comment by pawelfus** [comment] 2015-09-24 09:15
Duplicate of #4175.

**Closed by pawelfus** 2015-09-24 09:15 UTC
