### ISSUE TITLE
Chart width gets messed up when printing dialog closes, Chrome (Version 38)

### ISSUE THREAD

**Issue by finickee** [highslide-software/highcharts.com#3593] opened 2014-11-18 00:51 UTC
I am having issues with a project where I go to print a chart and when the print dialog closes (either by clicking print or cancel), the chart's width is overwritten with a much smaller value, making the chart skewed and messed up. I have read other bugs similar to this, but no real fix. Any ideas?
![before](https://cloud.githubusercontent.com/assets/9467527/5080779/22a497b4-6e93-11e4-9572-e49ca03cb20b.png)
![after](https://cloud.githubusercontent.com/assets/9467527/5080782/257370a0-6e93-11e4-9081-60ae427b5e5c.png)

**Comment by pawelfus** [comment] 2015-03-02 13:19
Looks like duplicate of #1093

**Comment by highslide-software** [comment] 2015-03-02 13:43
I can't reproduce #1093 now with Chrome 40. In order to understand what's going on, are you able to set up a live sample for us based on the screen shots above?

**Comment by highslide-software** [comment] 2015-03-02 14:43
#1093 was just closed. Please reopen if your issue persists.

**Closed by highslide-software** 2015-03-02 14:43 UTC
Labels: Pending reply
