### ISSUE TITLE
Stacked areaspline is rendered from the x-axis instead of the stacked series below it

### ISSUE THREAD

**Issue by mitar** [highslide-software/highcharts.com#4459] opened 2015-08-12 07:21 UTC
[See reproduction](http://jsfiddle.net/38gvcavr/). If you hover over the legend, you will see that charts are visually spanning from the x-axis up to their line. So as I hover over the legend to highlight series, the visualization is misleading. It looks like series are not stacked, but are on top of each other. This is exactly the opposite to what I wanted to achieve.

It is interesting that if I switch `areaspline` for just `area`, then it behaves as expected. Each series has correct lower edge as well. Only `areaspline` I am observing this issue.

**Comment by highslide-software** [comment] 2015-08-12 07:58
Yes, true stacking for `areaspline` is currently not implemented. This line turns it off: https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/parts/AreaSplineSeries.js#L12.

For your information, true stacking is being implemented in the `nosegments` branch, but we are still encountering problems when there are null values or different X values in the stack. [View it on jsFiddle](http://jsfiddle.net/highcharts/38gvcavr/1/).

**Comment by highslide-software** [comment] 2015-08-12 07:59
Duplicate of #1041.

**Closed by highslide-software** 2015-08-12 07:59 UTC
Labels: Duplicate
