### ISSUE TITLE
Flags overlap

### ISSUE THREAD

**Issue by niketh90** [highslide-software/highcharts.com#4676] opened 2015-10-21 13:20 UTC
Whenever highstocks flags are close by it overlaps. 
Consider the chart having 1000 points so close X axis point plots will have overlapping flags. 
Stackdistance doesnt work either.
![image](https://cloud.githubusercontent.com/assets/10894094/10637619/abe6a22e-77d4-11e5-8378-c9a0c1a3c5e0.png)

Please look into this asap.
Highstock JS v2.1.4 (2015-03-10)

Regards

Niketh

**Comment by pawelfus** [comment] 2015-10-21 13:25
Duplicate of #4674

**Closed by pawelfus** 2015-10-21 13:25 UTC
