### ISSUE TITLE
Javascript error with large y value that has high precision

### ISSUE THREAD

**Issue by thomassuckow** [highslide-software/highcharts.com#1515] opened 2013-02-14 19:38 UTC
When a large y value with high precision is used, toString includes the eXXX portion of the scientific notation. Spliting on . causes the eXXX portion to be counted in the length which results in a number greater than 20 and toFixed errors.

http://jsfiddle.net/fXV9V/

**Comment by pawelfus** [comment] 2015-08-17 10:42
Duplicate of #3793. Fixed in 4.1.2+

**Closed by pawelfus** 2015-08-17 10:42 UTC
Labels: Bug
