### ISSUE TITLE
Print page with chart issue

### ISSUE THREAD

**Issue by pliasetski** [highslide-software/highcharts.com#3248] opened 2014-07-11 09:21 UTC
Hello,

When I print webpage with chart ctr+p, not all chart area get printed.
https://dl.dropboxusercontent.com/u/73896408/Highcharts%20-%20Single%20line%20series.pdf

I have printed chart from this page: http://www.highcharts.com/stock/demo
Tested in chrome, FF and IE11

Thanks

**Comment by sebastianbochan** [comment] 2015-10-06 13:47
Duplicate of https://github.com/highslide-software/highcharts.com/issues/2088

**Closed by sebastianbochan** 2015-10-06 13:47 UTC
