### ISSUE TITLE
Exporting pie chart with size property set

### ISSUE THREAD

**Issue by madbull** [highslide-software/highcharts.com#4748] opened 2015-11-17 10:32 UTC
When you use size property on pie chart, some long labels doesn't fit to chart area after exporting.

http://jsfiddle.net/LLExL/5416/

**Comment by highslide-software** [comment] 2015-11-17 10:44
It isn't a problem with exporting per se, it is just that the exported chart has a different size. If you use the same size for both screen and export, you'll see the same thing: http://jsfiddle.net/highcharts/LLExL/5417/

**Comment by highslide-software** [comment] 2015-11-17 10:45
Duplicate of #1581

**Closed by highslide-software** 2015-11-17 10:45 UTC
Labels: Duplicate

**Comment by madbull** [comment] 2015-11-17 11:03
I see, thank you for the quick response
