### ISSUE TITLE
Column chart - double datalabels in export

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4330] opened 2015-06-26 09:36 UTC
Example: http://jsfiddle.net/r7L47830/

Chrome: 43.0.2357.130

**Comment by zhy1stgg** [comment] 2015-06-26 09:52
it's ok on my own exporting server, you can try it through  http://export.hcharts.cn
```
exporting: {
  url: 'http://export.hcharts.cn'
}
```

**Comment by pawelfus** [comment] 2015-06-26 10:25
Duplicate of #3649

**Closed by pawelfus** 2015-06-26 10:25 UTC
