### ISSUE TITLE
Click event not working on overlapped area chart

### ISSUE THREAD

**Issue by majuansari** [highslide-software/highcharts.com#4572] opened 2015-09-15 04:24 UTC
Hi,

I have a problem with the latest version of the highcharts plugin. The click event is not working on the overlapped part of the area chart. 

http://jsfiddle.net/maju/bvsv3ybb/2/

If you see the example you can the see the graph of USA ,which is overlapped by the graph of Russia, has its own markers. Hover is working fine but click event is not triggering.

Can any one help me with this ?

**Comment by pawelfus** [comment] 2015-09-15 12:10
Workaround:  set in CSS: 

.highcharts-series {
    pointer-events: none;
}

Example: http://jsfiddle.net/bvsv3ybb/4/

Duplicate of #3760.

**Closed by pawelfus** 2015-09-15 12:10 UTC

**Comment by majuansari** [comment] 2015-09-16 10:04
Hi ,

With relatively simpler example this work around will help

But please see the following jsfiddle for the chart which i generated

http://jsfiddle.net/maju/55beugej/

For most points the work around is working fine.But please see the marker with X value Oct'14 and Y value 1 and try to click on it. You can see that click event is not triggering

**Comment by pawelfus** [comment] 2015-09-16 11:00
It is a bit problematic - because tooltip is displayed for the blue point, but you click on the green one. That cause mismatched elements so click event isn't fired. 

Have you considered to use shared tooltip? Like this: http://jsfiddle.net/55beugej/1/
