### ISSUE TITLE
Looks like memory leak in using addPoint() on Stacked Area Chart (Actually crashed with massive data)

### ISSUE THREAD

**Issue by yeoupooh** [highslide-software/highcharts.com#4241] opened 2015-05-29 02:13 UTC
You can reproduce the issue from below example by triggering animation.

Example: http://jsfiddle.net/yeoupooh/o00hm0m4/

I can see memory usage increasing from Chrome task manager. Peak memory size is slightly(10~30k) increased in 10 minutes. But in real life, more points and more series could be used. So out of memory could be reached sooner.

Thank you in advance.

**Comment by yeoupooh** [comment] 2015-06-08 01:02
Hi, 

I've added more points on the example to reproduce the crash more quickly.

http://jsfiddle.net/yeoupooh/o00hm0m4/4/

On both IE11, Chrome 43 were crashed after several hours. (Don't know exact time but It was crashed during weekend)

This is critical for monitoring applications that shows these kinds of charts always should be displayed on monitor.

By the way, could I have an workaround for using stacked area(line) charts?

Best Regards,
Thomas

**Comment by highslide-software** [comment] 2015-07-01 13:49
Duplicate of #4320 (or the other way around). We will follow up there, where more information is provided.

**Closed by highslide-software** 2015-07-01 13:49 UTC
