### ISSUE TITLE
numberFormat with really small values: toFixed() digits argument must be between 0 and 20

### ISSUE THREAD

**Issue by Cyriuz** [highslide-software/highcharts.com#3661] opened 2014-12-16 11:58 UTC
I'm using highstock 2.0.4 and have a chart which sometimes may contain really small values. When the yAxis for these values is generated it seems that they are sometimes generated with more than 20 decimals which causes this crash in highstocks numberFormater on line 377. I haven't been able to reproduce it consistently so I can't provide an example but looking at the code I think it would have been good with a check for the decimal amount as it is dynamically calculated.

![highstock-issue](https://cloud.githubusercontent.com/assets/5775426/5453076/ecaed678-8522-11e4-997b-f74b135ac052.png)
The image is from a previous version of highstock so the line number is not 377 here but it is the same issue as with 2.0.4, I just tried upgrading but see the same issue.

**Comment by pawelfus** [comment] 2015-08-17 10:42
Duplicate of #3793. Fixed in 4.1.2+

**Closed by pawelfus** 2015-08-17 10:42 UTC
